# Generated by Django 3.0.8 on 2020-08-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_has_variants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='has_variants',
            new_name='book_format',
        ),
    ]
